### ISSUE TITLE
Sort awards

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/awards#28]
The order of the displayed awards seems pretty random.

I suggest to implement a fully automated sorting algorithm to sort all awards, based on their contents.
The sorting could be done in multiple “passes”.
In the first pass, sort awards by “secrecy”. Non-secret awards or awards which are secret but have been gotten come first, and all secret awards come at the end. This is done to avoid giving away clues.
In the second pass, sort the revealed achievements by type/trigger (craft, dig, place, no type, etc.). The order doesn't matter much here, what's important to me that achievements of the same type are grouped together.
In the third pass, _within each type_, sort the achievements by some type-specific values (if applicable).

The idea of this sorting is that similar awards are close to each other. The current practice of showing all earned awards at the beginning should be dropped, as this would defeat the purpose of this algorithm.

For type-specific sorting, I suggest these rules:
- Dig: First sort alphabetically by node type, then by node count
- Place: Same as dig
- Craft: Same as dig, except we first sort by item type alphabetically
- Die: Sort by death count
- Join: Sort by join count
- Chat: Sort by message count

Example: A finished sorting could look like this:
- Dig 10 dirt
- Dig 20 dirt
- Dig 200 dirt
- Dig 1 torch
- Dig 8 wool
- Place 5 rails
- Place 10 rails
- Craft 9 lamps
- Die 10 times
- Die 100 times
- Join the server 2 times
- Reach a height of 1,000 (custom award without predefined trigger)
- Ignite TNT (another custom award)
- (Secret Award)
- (Secret Award)

Note: Awards without type/trigger are considered to have their own “type” and are thus grouped together as well. There is no particular sorting for these awards.

Do you agree? Do you have anything to add? Please discuss.

**Comment by rubenwardy** [comment]
What about awards for mods like mesecons, moreblocks, etc? Would it not make more sense to put them together?

**Comment by rubenwardy** [comment]
I agree with putting secret unknown awards at the end

**Comment by Wuzzy2** [comment]
> What about awards for mods like mesecons, moreblocks, etc? Would it not make more sense to put them together?

I don't think it would be a good idea in the first place. Minetest Game alone has lots of mods, so including mod origin into the sorting would probably mess things up too much, especially since these mods are so closely related, the difference is uninteresting for the player. Also, Mesecons is a modpack with many mods, the same problem would therefore apply as well. The difference between each single mod is to small to be considered for sorting.

Mod origin is too technical and too internal for my taste, many players don't care about the mod origin and they probably would not understand the logic behind the sorting. This effect will be amplified when playing on a server, since servers often have many mods you have never seen before.

However, a sorting based on trigger (=goal type) is much more obvious to players IMO.

**Comment by rubenwardy** [comment]
I agree that everything packaged by default in awards should be sorted by trigger - and sorting everything by trigger would be better than what we currently have

**Comment by rubenwardy** [comment]
Feedback from agaran on IRC:

> second, sorting awards by amount of thing to dig or other similar criteria in list would be nice, so big-count awards appear lower in list than first 100 blocks dug.. etc

http://irc.minetest.ru/minetest/2016-09-17#i_4705741

**Comment by numberZero** [comment]
Are there any chances for this to be implemented?

**Comment by bell07** [comment]
My idea / proposal is 

Started awards should be sorted by % completeness at the first. So the order be produced automatically
Dig 10 dirt ( => 10%)
Dig 20 dirt (=> 5%)
Dig 200 dirt (=> 0.5%)

The completed awards (100%) should be sorted by completition timestamp.
Started awards with same % should be sorted by timestamp the % was reached.

The not started awards (0%) should be sorted by "difficulty level" that may should be added to the awards definitions.

**Comment by bell07** [comment]
Additional idea for sorting weight of 0% without difficulty level: Add a small value to the counter (hard-coded 0.1?)

0 digged dirt
Dig 1 dirt (0.1/1*100 = 10)
Dig 10 dirt ( 0.1/10*100 = 1)
Dig 20 dirt ( 0.1/20*100 = 0.5)
Dig 200 dirt (0.1/20*100 = 0.05)

1 digged stone
Dig 1 stone (1+0.1)/1*100 = 110
Dig 10 stone (1+0.1)/10*100 = 11
Dig 20 stone (1+0.1)/20*100 = 5.5
Dig 200 stone (1+0.1)/20*100 = 0.55
Output Order:
Dig 1 stone (completed)
Dig 10 stone
Dig 1 dirt
Dig 20 stone
Dig 10 dirt
Dig 200 stone
Dig 20 dirt
Dig 200 dirt

Maybe an other additional value needs to be found, or only the 0% values are sorted this way

**Comment by rubenwardy** [comment]
```lua
local score
if def.secret then
	score = 1000000
elseif def.trigger and def.trigger.target and def.getProgress then
	local progress = def:getProgress(data).perc
	score = (1 - progress) * def.trigger.target
	if progress < 0.001 then
		score = score + 100  -- not started yet, penalise
	end
else
	score = 100
end
```
