### ISSUE TITLE
bug "/awards disable" in 2.3.0 

### ISSUE THREAD

**Issue by justtestrestoration** [minetest-mods/awards#33]
The way I reproduced this bug was, I logged in as a regular player on the server, then I did the following commands:
1. /awards disable
2. /awards

after that I got the following crash

`ERROR[Main]: ServerError: Lua: Runtime error from mod 'awards' in callback on_chat_message(): /mods/awards/api.lua:406: bad argument #2 to 'chat_send_player' (string expected, got no value)`

If you can reproduce this or if it works fine for you without any crashes, with latest stable 2.3.0, please let me know

**Comment by rubenwardy** [comment]
Found the bug: `minetest.chat_send_player("You've disabled awards. Type /awards" ..
				" enable to reenable")`
