### ISSUE TITLE
Relicensing as MIT

### ISSUE THREAD

**Issue by rubenwardy** [minetest-mods/awards#37]
Using LGPL means that WTPL/etc subgames can't use this mod.
It's very useful to have one common mod to do a thing, and act as a library - sharing code and a API, shared bug fixes, etc.

Do you think this overrules the benefits of LGPL?
Would people find this useful?

All contributors:

- [X] @Calinou 
- [X] @Wuzzy2 
- [X] @MrIbby 
- [X] @Traxie21 (contributions removed)
- [x] @kaeza 
- [x] @kingoscargames 
- [x] @EdwardThorsten

**Comment by rubenwardy** [comment]
I'd also like @kaadmy's feedback, as he's made an alternative to awards with a WTFPL license. Did you do that because this was LGPL, or was it because of other concerns?

Awards certainly has a DRY problem, especially in triggers.lua that I'd like to solve

**Comment by kaadmy** [comment]
Which of my mods are you talking about? My achievements mod in Pixture?
I've relicensed it as LGPL a while back, it doesn't have any copied/preexisting code from anything else.

**Comment by Wuzzy2** [comment]
:+1:

**Comment by MrIbby** [comment]
I'm fine with either license.

**Comment by Calinou** [comment]
I'm OK with a license change to MIT.

**Comment by kaeza** [comment]
:+1: from me.

**Comment by AntumDeluge** [comment]
I'm not a contributor, but MIT is my license of choice. So 👍 from me. 😃
