### ISSUE TITLE
Remove impossible nyan cat achievement

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/awards#44]
The nyan cat achievement should be removed because the nyan cat has been removed from Minetest Game 0.4.16.
Otherwise, there would be an impossible achievement.

**Comment by gejan** [comment]
I think it should rather be replaced by a "PB&J Pup" achievement

**Comment by Wuzzy2** [comment]
PB&J Pup has been removed as well.

If PB&J Pup is in an external mod now, the achievement should be added there, not in the `awards` mod.
