### ISSUE TITLE
Award dependency trees

### ISSUE THREAD

**Issue by bell07** [minetest-mods/awards#52]
looking forward from #28 the award sequences could be supported too in dynamic hiding to get more visual clarity. An award sequence is an awards group like 
1. Dig 1 dirt
2. Dig 10 dirt
3. Dig 20 dirt
4. Dig 200 dirt
5. Dig 1000 dirt

If no dirt was digged, only the award 1 (next) is visible, all other are hidden.
If award 1 is reached, the award 1 (completed) and 2 (next) are visible.
If award 2 is reached, award 1 is hidden, 2 (completed) and 3 (next) are visible, the 4,5 are still hidden.
If the last award 5 is reached, only the 5 (completed) remains visible.

**Comment by numberZero** [comment]
That sounds more like “multi-level” award. As in some modern games, where you can complete a level with different rating (e.g. 1 to 3 stars).

**Comment by rubenwardy** [comment]
Yeah, I'm wondering whether this should actually be displayed in one award as a rating, and the progress to the next rating.

**Comment by bell07** [comment]
An award sequence could be not linear, like

1. dig stone
2. dig tree
3. craft furnance
4. smelt steel
5. craft steel axe

Maybe something like dependency tree?

3 requires 1
4 requres 3
5 requires 2 and 4

...

Hide open awards if not all dependencies reached (Show 5 only if 2 AND 4 reached)
Hide completed awards if "next" awards exits and all reached (Hide 1 if 3 is reached)

**Comment by numberZero** [comment]
You don’t need to dig a tree to craft an axe, you could get sticks in some other way.

**Comment by bell07** [comment]
> You don’t have to dig a tree to craft an axe, you could get sticks in some other way.

This was an example, but you are right, the player can always find ways to skip current award and reach the next one. In multiplayer really easy because you can obtain items and use furnances from other players.

The question is the expected mod behaviour in this case.
1. you cannot reach the award till the award is "unlocked". Means all axe craftings are ignored till the "dig a tree" is reached (as implemented?)
2. Award is just hidden, but reachable (unlocked on reach). That means if an axe is crafted before "dig a tree", the award appears and will be visible (my initial expectation)
3. The award is reachable, but remains hidden if reached. That means if you craft the axe, you do not get the award instantly. If you dig the tree after them, you get both awards because both reached. (behaviour seen in some mobile games, multiple awards appears if an outstanding award is reached,

I prefer 3 for now

@rubenwardy do you reopen this issue or should a new issue be open?

**Comment by numberZero** [comment]
I prefer (2). The behavior you describe in (3) is annoying.

В Thu, 05 Apr 2018 21:00:09 -0700
bell07 <notifications@github.com> пишет:

> > You don’t have to dig a tree to craft an axe, you could get sticks
> > in some other way.
> 
> This was an example, but you are right, the player can always find
> ways to skip current award and reach the next one. In multiplayer
> really easy because you can obtain items and use furnances from other
> players.
> 
> The question is the expected mod behaviour in this case.
> 1. you cannot reach the award till the award is "unlocked". Means all
> axe craftings are ignored till the "dig a tree" is reached (as
> implemented?) 2. Award is just hidden, but reachable (unlocked on
> reach). That means if an axe is crafted before "dig a tree", the
> award appears and will be visible (my initial expectation) 3. The
> award is reachable, but remains hidden if reached. That means if you
> craft the axe, you do not get the award instantly. If you dig the
> tree after them, you get both awards because both reached. (behaviour
> seen in some mobile games, multiple awards appears if an outstanding
> award is reached,
> 
> I prefer 3 for now
> 
> @rubenwardy do you reopen this issue or should a new issue be open?
>
